# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bdpan < Formula
  desc "百度网盘命令行工具"
  homepage "https://github.com/wxnacy/bdpan-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.4/bdpan_0.0.4_darwin_amd64.tar.gz"
      sha256 "e960e82f58cbe66f2f05efbad297ab2472be6c7b14a72dc36adeb08a1a0fa5da"

      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.4/bdpan_0.0.4_darwin_arm64.tar.gz"
      sha256 "95b2d5fcd61764c06c464d7692576242cbf0dcf7c9853c7668051ebb095dc759"

      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.4/bdpan_0.0.4_linux_amd64.tar.gz"
      sha256 "3b102b0f40915f54dd1137d937cd6eeef2787ac02bd7d39a8831efeff68c30c6"
      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.4/bdpan_0.0.4_linux_arm64.tar.gz"
      sha256 "35b42f83faa570857ee0487f5cb4bce1079aeb5ebd3f9fbd7f50bca3f73ae7d3"
      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
  end
end
