# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bdpan < Formula
  desc "百度网盘命令行工具"
  homepage "https://github.com/wxnacy/bdpan-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.3/bdpan_0.0.3_darwin_amd64.tar.gz"
      sha256 "100950f51ef06567621f0e428ee1bbdbc96c584a4cc49902129aac33d6fb57af"

      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.3/bdpan_0.0.3_darwin_arm64.tar.gz"
      sha256 "0a3f5428a1bb1a96dfbdba6cd0ba87fe06b12f9e788886bd0ad2ca9ef126e323"

      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.3/bdpan_0.0.3_linux_amd64.tar.gz"
      sha256 "cf2fbff63da862139ac47525217d6e70cce7daf0daf465a964e5ac25b5f4dbd5"
      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/bdpan-cli/releases/download/v0.0.3/bdpan_0.0.3_linux_arm64.tar.gz"
      sha256 "edcaf7b7d46cd1dcf1f358e2a3182815e00277461dd64c61699b5c1ed1fc0d02"
      def install
        bin.install "bdpan"
        generate_completions_from_executable(bin/"bdpan", "completion", base_name: "bdpan")
      end
    end
  end
end
