# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgo < Formula
  desc "类 IPython 的 Golang 交互运行工具"
  homepage "https://github.com/wxnacy/wgo"
  version "1.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.9/wgo_1.2.9_darwin_amd64.tar.gz"
      sha256 "1032b87d29e4d33d8b6d4df033f2f0991aa927f8f730d7e1ecfc22b6fb365a1b"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.9/wgo_1.2.9_darwin_arm64.tar.gz"
      sha256 "3f42deddf85c12514b9137afe0ade4e246b46bb7c96f58b4886968555f934ec9"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.9/wgo_1.2.9_linux_amd64.tar.gz"
      sha256 "b403d8b1ef18539c6117ccd531fff4afbbccc51d24c2f4328460275a9912fe95"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.9/wgo_1.2.9_linux_arm64.tar.gz"
      sha256 "dec794c5b1e6d39f04da5ff90fd6558737a762f2386d751b7b7608c73fa19801"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  def caveats
    <<~EOS
      代码补全依赖 gopls：
        brew install gopls
        或
        go install golang.org/x/tools/gopls@latest
    EOS
  end
end
