# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgo < Formula
  desc "类 IPython 的 Golang 交互运行工具"
  homepage "https://github.com/wxnacy/wgo"
  version "1.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.5/wgo_1.2.5_darwin_amd64.tar.gz"
      sha256 "a5dc8a98001f465c6ee1b080f663ebec5f72b0b21ed2e140e49f865db1880ae6"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.5/wgo_1.2.5_darwin_arm64.tar.gz"
      sha256 "35c20071a0f4fbd9944bf26bd7020d99f1750b5e670ae5ba1293fc14f280441f"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.5/wgo_1.2.5_linux_amd64.tar.gz"
      sha256 "9e12288f4b87acd8349786ce4c329092a956a2719013dd609126ff1b1d571707"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.5/wgo_1.2.5_linux_arm64.tar.gz"
      sha256 "0ad675690cb1a26546d9a084fbd47da17bc97b68db1d8040a5439bb23886260d"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  def caveats
    <<~EOS
      代码补全依赖 gopls：
        brew install gopls
        或
        go install golang.org/x/tools/gopls@latest

      自动导入/格式化依赖 goimports：
        go install golang.org/x/tools/cmd/goimports@latest
    EOS
  end
end
