# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgo < Formula
  desc "类 IPython 的 Golang 交互运行工具"
  homepage "https://github.com/wxnacy/wgo"
  version "1.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.8/wgo_1.2.8_darwin_amd64.tar.gz"
      sha256 "902af5fcf43275490d7f793e30247cf616b1c9fd930645a54dcb93c69a059bfc"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.8/wgo_1.2.8_darwin_arm64.tar.gz"
      sha256 "9f5e28836cb4e2205a57cc17b98afb4d8680116aa101409ac9bd0aedcebd79ef"

      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.8/wgo_1.2.8_linux_amd64.tar.gz"
      sha256 "018b4f7e6806eebfea4a7f4cbf1e7f71b545c75537442ccbe41d832e5ce51433"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wxnacy/wgo/releases/download/v1.2.8/wgo_1.2.8_linux_arm64.tar.gz"
      sha256 "b52e8f31357f168827f5594a61b679331eaa3f26df1f734d222135c3294d0aca"
      def install
        bin.install "wgo"
        # 通过可执行文件生成 bash/zsh/fish/powershell 补全
        generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
      end
    end
  end

  def caveats
    <<~EOS
      代码补全依赖 gopls：
        brew install gopls
        或
        go install golang.org/x/tools/gopls@latest
    EOS
  end
end
